version: '3.8'
services:
  app:
    build: ./Application
    container_name: "Flask_App"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "MySQL_Database"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: persist
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro